/* Copyright © 2016 EIS Group and/or one of its affiliates. All rights reserved. Unpublished work under U.S. copyright laws.
 CONFIDENTIAL AND TRADE SECRET INFORMATION. No portion of this work may be copied, distributed, modified, or incorporated into any other media without EIS Group prior written consent.*/
package org.apache.myfaces.renderkit.html.util;

import java.io.IOException;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * A class which can interpret the URI generated by a corresponding ResourceHandler
 * implementation, locate that resource and write it to the servlet response stream.
 *
 * @author Mathias Broekelmann (latest modification by $Author: skitching $)
 * @version $Revision: 673833 $ $Date: 2008-07-04 00:58:05 +0300 (Fri, 04 Jul 2008) $
 */
public interface ResourceLoader
{
    /**
     * Define an exception for reporting when a client requests a resource, but
     * then closes its socket before we finish sending it. In this case, the normal
     * behaviour is to not report an error; there is nothing wrong on this end. 
     */
    public static class ClosedSocketException extends IOException
    {
    }

    /**
     * Called by AddResource to render external resource data 
     * @param context TODO
     * @param request the request 
     * @param response the response to write the resource content to
     * @param resourceUri contains the uri part after the uri which 
     * is used to identify the resource loader
     * 
     * @throws IOException
     */
    public void serveResource(ServletContext context, HttpServletRequest request,
            HttpServletResponse response, String resourceUri) throws IOException;
}
