/* Copyright © 2016 EIS Group and/or one of its affiliates. All rights reserved. Unpublished work under U.S. copyright laws.
 CONFIDENTIAL AND TRADE SECRET INFORMATION. No portion of this work may be copied, distributed, modified, or incorporated into any other media without EIS Group prior written consent.*/
package javax.faces.component.html;

import org.apache.myfaces.buildtools.maven2.plugin.builder.annotation.JSFProperty;

interface _LinkProperties
{
    /**
     * HTML: Specifies the character encoding of the linked resource.
     * 
     */
    @JSFProperty
    public abstract String getCharset();
    
    /**
     * HTML: The coordinates of regions within a client side image map.
     * 
     */
    @JSFProperty
    public abstract String getCoords();
    
    /**
     * HTML: The language of the linked resource.
     * 
     */
    @JSFProperty
    public abstract String getHreflang();
    
    /**
     * HTML: The relationship between the current document and
     * the linked resource.
     *
     */
    @JSFProperty
    public abstract String getRel();
    
    /**
     * HTML: The type(s) describing the reverse link for the linked
     * resource.
     * 
     */
    @JSFProperty
    public abstract String getRev();
    
    /**
     * HTML: The shape of a region in a client side image map.
     * 
     */
    @JSFProperty
    public abstract String getShape();
    
    /**
     * HTML: Names the frame that should display content generated by invoking this action. 
     * 
     */
    @JSFProperty
    public abstract String getTarget();
    
    /**
     * HTML: A hint to the user agent about the content type of the linked resource.
     * 
     */
    @JSFProperty
    public abstract String getType();

    /**
     * When true, this element cannot receive focus.
     *
     * @return  the new disabled value
     */
    @JSFProperty
    (defaultValue = "false")
    public abstract boolean isDisabled();

}
